// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MustafaGuler.Repository.Contexts;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MustafaGuler.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251205134757_SeedDataAdded")]
    partial class SeedDataAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MustafaGuler.Core.Entities.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("TestDescription")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Content = "Onion Architecture, yazılım projelerinde bağımlılıkları yönetmek için...",
                            CreatedDate = new DateTime(2023, 10, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            GroupId = new Guid("99999999-9999-9999-9999-999999999999"),
                            IsDeleted = false,
                            LanguageCode = "tr",
                            Title = "Onion Architecture Nedir?",
                            ViewCount = 100
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Content = "Onion Architecture is a layered architecture pattern...",
                            CreatedDate = new DateTime(2023, 10, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            GroupId = new Guid("99999999-9999-9999-9999-999999999999"),
                            IsDeleted = false,
                            LanguageCode = "en",
                            Title = "What is Onion Architecture?",
                            ViewCount = 50
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
