// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MustafaGuler.Repository.Contexts;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MustafaGuler.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251205150129_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MustafaGuler.Core.Entities.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CategoryId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Content = "Türkçe içerik...",
                            CreatedDate = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            GroupId = new Guid("99999999-9999-9999-9999-999999999999"),
                            IsDeleted = false,
                            LanguageCode = "tr",
                            Title = "Onion Architecture Nedir?",
                            ViewCount = 100
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CategoryId = new Guid("44444444-4444-4444-4444-444444444445"),
                            Content = "English content...",
                            CreatedDate = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            GroupId = new Guid("99999999-9999-9999-9999-999999999999"),
                            IsDeleted = false,
                            LanguageCode = "en",
                            Title = "What is Onion Architecture?",
                            ViewCount = 50
                        });
                });

            modelBuilder.Entity("MustafaGuler.Core.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedDate = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Teknik makaleler.",
                            IsDeleted = false,
                            Name = "Yazılım Dünyası",
                            Slug = "yazilim-dunyasi"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333334"),
                            CreatedDate = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Technical articles.",
                            IsDeleted = false,
                            Name = "Software World",
                            Slug = "software-world"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedDate = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = ".NET ve Mimari.",
                            IsDeleted = false,
                            Name = "Backend Geliştirme",
                            ParentId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Slug = "backend-gelistirme"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444445"),
                            CreatedDate = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = ".NET and Architecture.",
                            IsDeleted = false,
                            Name = "Backend Development",
                            ParentId = new Guid("33333333-3333-3333-3333-333333333334"),
                            Slug = "backend-development"
                        });
                });

            modelBuilder.Entity("MustafaGuler.Core.Entities.Article", b =>
                {
                    b.HasOne("MustafaGuler.Core.Entities.Category", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MustafaGuler.Core.Entities.Category", b =>
                {
                    b.HasOne("MustafaGuler.Core.Entities.Category", "Parent")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("MustafaGuler.Core.Entities.Category", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("SubCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
